name: dino_game
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/dino.png
    - assets/cactus.png
    - assets/background.png
    - assets/jump.mp3
    - assets/crash.mp3
    - assets/bgm.mp3
    - assets/gameover.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon:
    foreground_image: "assets/app_icon.png"
    background: "#FFFFFF" # You can specify a color or use a drawable resource
  # Add the following lines to specify the adaptive icon

