name: dino_game
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^4.1.0
  shared_preferences: ^2.0.6
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/dino.png
    - assets/cactus.png
    - assets/background.png
    - assets/jump.mp3
    - assets/crash.mp3
    - assets/bgm.mp3
    - assets/gameover.mp3
    - assets/start_screen_image.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon:
    foreground_image: "assets/app_icon.png"
    background: "#FFFFFF"
  remove_alpha_ios: true
